### ISSUE TITLE
Error response from daemon: manifest for reactnativecommunity/react-native-android:7.1.1 not found: manifest unknown

### ISSUE THREAD

**Issue by gupta-ji6** [react-native-community/react-native-circleci-orb#176]
### Orb version

[react-native-community/react-native@7.1.1](https://circleci.com/developer/orbs/orb/react-native-community/react-native)

### What happened

We were using `reactnativecommunity/react-native-android:7.0` docker image which worked smoothly. I tried updating it to `7.1.1`, `7.1`, and `7.1.0` but all resulted in "manifest not found error". Sharing the config & error stack trace below. What am I missing?

<details>
<summary>config.yml</summary>

```yml
version: 2.1

parameters:
  rn_android_docker_version:
    default: "7.0" # Refer - https://github.com/react-native-community/react-native-circleci-orb
    type: string

orbs:
  node: circleci/node@5.0.0
  slack: circleci/slack@4.8.3

executors:
  linux_android:
    parameters:
      gradle_options:
        description: Gradle command options. Disables Gradle Daemon for CI environment as we are building the app only once per CI run.
        type: string
        default: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=4"
      resource_class:
        description: Changes the resource class of the executor. Resource class docs  https://circleci.com/docs/2.0/configuration-reference/#resource_class
        type: string
        default: xlarge
    resource_class: <<parameters.resource_class>>
    environment:
      - GRADLE_OPTS: <<parameters.gradle_options>>
    docker:
      - image: reactnativecommunity/react-native-android:<< pipeline.parameters.rn_android_docker_version >>
```

</details>

<details>
<summary>Error</summary>

```
Build-agent version 1.0.198461-d5700ca4 (2023-08-21T16:56:08+0000).
System information:
 Server Version: 20.10.18
 Storage Driver: overlay2
  Backing Filesystem: xfs
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Kernel Version: 5.15.0-1039-aws
 Operating System: Ubuntu 20.04.6 LTS
 OSType: linux
 Architecture: x86_64

Starting container reactnativecommunity/react-native-android:7.1.1
Warning: No authentication provided, using CircleCI credentials for pulls from Docker Hub.
  image cache not found on this host, downloading reactnativecommunity/react-native-android:7.1.1

Error response from daemon: manifest for reactnativecommunity/react-native-android:7.1.1 not found: manifest unknown: manifest unknown
```

</details>

### Expected behavior

The [`7.1` version](https://github.com/react-native-community/react-native-circleci-orb/releases/tag/v7.1.0) should have worked same as `7.0` did.
