### ISSUE TITLE
How to pass parameters to an executor?

### ISSUE THREAD

**Issue by compojoom** [react-native-community/react-native-circleci-orb#21]
# Question
Hi, our build fails on circleci. After debugging for some time I figured out that I would have to set different _JAVA_OPTIONS and GRADLE_OPT than specified in the linux_android executor.

From the docs over here I can see that the executor has parameters, but I'm failing to see how to set those?
https://circleci.com/orbs/registry/orb/react-native-community/react-native#executors-linux_android

Is it at all possible to override those parameters from outside?

**Comment by compojoom** [comment]
To answer my own question. One need to create a new job and specify the executor there. Then you can pass parameters to the executor.
```
jobs:
  #.....
  my_android_build:
    executor:
      name: rn/linux_android
      gradle_options: '-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8'
      java_options: '-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8'
      build_threads: 2
    parameters:
      project_path:
        description: The path to the root of the Android project you want to build, relative to the root of the repository.
        type: string
        default: "./android"
      build_type:
        description: The build type to build. This is normally either "debug" or "release" but you may have custom build types configured for your app.
        type: string
        default: "debug"
    steps:
      - checkout
      - attach_workspace:
          at: .
      - rn/yarn_install
      - rn/android_build:
          build_type: <<parameters.build_type>>
          project_path: <<parameters.project_path>>
```

Sadly there is no way to just use the android_build job and pass executor params there...
