### ISSUE TITLE
Detox test on iOS

### ISSUE THREAD

**Issue by roni-castro** [react-native-community/react-native-circleci-orb#29]
# Question

All the steps to build and test my iOS app on CircleCi have succeeded, except for the 
"Detox Test "one.
Do I need to add any configuration to run this last step (Install Detox lib)? 
Is it possible to just build the iOS and not run the Detox commands (`Configure Detox Environment` and `Detox tests`) as I use Jest+ Enzyme to do it?

![CircleCi result print](https://user-images.githubusercontent.com/24610813/71602934-45a82880-2b39-11ea-89bc-354275665a28.png)

```
#!/bin/bash --login -eo pipefail
detox test -c ios.sim.release -l warn --headless
/bin/bash: detox: command not found

Exited with code exit status 127
```

Version:
react-native-community/react-native@1.3.0
react-native: 0.59.9

.config.yml
```
      - rn/ios_build_and_test:
          # <<: *master_only
          project_path: ios/OlistApp.xcodeproj
          device: iPhone X
          build_configuration: Debug
          scheme: OlistApp
          detox_configuration: ios.sim.release
          requires:
            - analyse_js
```
