### ISSUE TITLE
Node version mismatch with the rn/ios_build job

### ISSUE THREAD

**Issue by kkotowick** [react-native-community/react-native-circleci-orb#38]
### Orb version

3.0.0

### What happened

Executor has Node v11.0.0 installed, even when v10 specified for the `rn/ios_build` job.

### Expected behavior

Node v10 should be installed.

### Reproduction:

This is my config file:

```
version: 2.1

orbs:
    rn: react-native-community/react-native@3.0.0

workflows:
    version: 2
    buildit:
        jobs:
            - rn/ios_build:
                build_configuration: Release
                device: Generic iOS Device
                name: build_ios_release
                project_path: ios/MyProject.xcodeproj
                scheme: release
                checkout: true
```

And this is my output from the [Configure Detox Envionment](https://github.com/react-native-community/react-native-circleci-orb/blob/dd7046ad55b2612c4396cb7fe512ec1a709851f2/src/commands/setup_macos_executor.yml#L25) step in the pipeline:

```
#!/bin/bash --login -eo pipefail
HOMEBREW_NO_AUTO_UPDATE=1 brew tap wix/brew >/dev/null
HOMEBREW_NO_AUTO_UPDATE=1 brew tap homebrew/cask >/dev/null
HOMEBREW_NO_AUTO_UPDATE=1 brew install node@10 >/dev/null
HOMEBREW_NO_AUTO_UPDATE=1 brew install applesimutils >/dev/null
HOMEBREW_NO_AUTO_UPDATE=1 brew cask install android-sdk >/dev/null
touch .watchmanconfig
node -v

v11.0.0
CircleCI received exit code 0
```

As you can see, even though this orb defaults to Node v10, it seems like Node v11 is getting installed. Perhaps Node v11 is now installed by default on CircleCI's Mac executors? I'm not sure why else an install of `node@10` would result in `node -v` returning `v11.0.0`.
