### ISSUE TITLE
Tests fail - applesimutils is unable to list simulators

### ISSUE THREAD

**Issue by kg-currenxie** [react-native-community/react-native-circleci-orb#43]
### Orb version

react-native-community/react-native@3.0.1

### What happened

Test failed to start

```
#!/bin/bash --login -eo pipefail
detox test -c ios.debug -l warn --headless
v10.19.0 is already installed.
Now using node v10.19.0 (npm v6.13.4)
default -> 10 (-> v10.19.0 *)
detox[14565] INFO:  [test.js] configuration="ios.debug" loglevel="warn" headless=true reportSpecs=true DETOX_START_TIMESTAMP=1581674270596 node_modules/.bin/jest --config e2e/config.json '--testNamePattern=^((?!:android:).)*$' --maxWorkers 1 "e2e"
detox[15132] ERROR: [exec.js/EXEC_FAIL, #0] "applesimutils --list --byType "iPhone Xs"" failed with code = 255, stdout and stderr:

detox[15132] ERROR: [exec.js/EXEC_FAIL, #0] 
detox[15132] ERROR: [exec.js/EXEC_FAIL, #0] v10.19.0 is already installed.
Error: The data couldn’t be read because it isn’t in the correct format.. See “applesimutils --help” for usage.

Error: Unable to obtain a list of simulators. See “applesimutils --help” for usage.


detox[15132] ERROR: [DetoxExportWrapper.js/DETOX_INIT_ERROR] 
 { ChildProcessError: Command failed: applesimutils --list --byType "iPhone Xs"
v10.19.0 is already installed.
Error: The data couldn’t be read because it isn’t in the correct format.. See “applesimutils --help” for usage.

Error: Unable to obtain a list of simulators. See “applesimutils --help” for usage.

 `applesimutils --list --byType "iPhone Xs"` (exited with error code 255)
    at callback (/Users/distiller/project/node_modules/child-process-promise/lib/index.js:33:27)
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  name: 'ChildProcessError',
  code: 255,
```

### Expected behavior

It should not error :)

```
executors:
  macos:
    macos:
      xcode: 11.2.1

workflows:
  Build and Test:
    jobs:
      - rn/ios_build_and_test:
          name: test_ios_debug
          project_path: ios/Example.xcworkspace
          project_type: workspace
          device: "iPhone XS"
          build_configuration: Debug
          scheme: "Example'"
          detox_configuration: ios.debug
          requires:
            - build_ios_debug
```
