### ISSUE TITLE
Setting node_version is ignored at ios_build_and_test

### ISSUE THREAD

**Issue by MateusAndrade** [react-native-community/react-native-circleci-orb#51]
### Orb version
 4.1.0
 
### What happened

Whenever I use the job `ios_build_and_test`:

```yml
      - react-native/ios_build_and_test:
          checkout: true
          build_configuration: Release
          detox_configuration: ios.sim.release
          device: iPhone X
          node_version: '10.17'
          project_path: ios/AppName.xcworkspace
          requires:
            - another-command
          scheme: AppName
```

When the job runs https://github.com/react-native-community/react-native-circleci-orb/blob/a9ca7c9ca807632025e13d4e9c16ad782cb0c563/src/jobs/ios_build_and_test.yml#L85

I got an error, because of a dependency on my project, requires using the `node_version` < `10.17`.

I saw that whenever you call:

https://github.com/react-native-community/react-native-circleci-orb/blob/a9ca7c9ca807632025e13d4e9c16ad782cb0c563/src/commands/setup_macos_executor.yml#L25-L37

He will fetch nvm and set the version on macos `11.0.0` executor. But on the subsequent job, that shows the `node -v`, you still got the default version of the macos executor. With is: `12.0`.

https://circle-macos-docs.s3.amazonaws.com/image-manifest/v1969/index.html

### Expected behavior

Calling `yarn_install` passing `node_version` at `ios_build_and_test` would save the version to subsequent jobs.

Maybe we can add a parameter to check if I want a specific version of node when calling `yarn_install`.

# ScreenShots 

![Screen Shot 2020-04-17 at 16 37 28](https://user-images.githubusercontent.com/15278828/79607544-c0398b80-80c9-11ea-913e-528a18908940.png)
