### ISSUE TITLE
Emulator does not run

### ISSUE THREAD

**Issue by azizhk** [react-native-community/react-native-circleci-orb#53]
### Orb version
v4.1.0

### What happened
Emulator does not seem to be running.
My circleci config:
```yml
version: 2.1
orbs:
  rn: react-native-community/react-native@4.1.0
jobs:
  detox_test:
    environment:
      CACHE_VERSION: 2
    executor:
      name: rn/linux_android
    steps:
      - checkout
      - rn/yarn_install
      - run:
          command: yarn jetify
      - rn/android_emulator_start
      - rn/detox_test:
          configuration: android.emu.debug
      - persist_to_workspace:
          paths: .
          root: .

workflows:
  test:
    jobs:
      - detox_test
```

Getting the following output:
```
#!/bin/bash -eo pipefail
/usr/local/share/android-sdk/emulator/emulator @TestingAVD -version
/usr/local/share/android-sdk/emulator/emulator @TestingAVD -skin 470x860 -cores 1 -gpu auto -accel on -memory 1024 -no-audio -no-snapshot -no-boot-anim -no-window -logcat *:W | grep -i 'ReactNative\|com.reactnativecommunity'

/bin/bash: /usr/local/share/android-sdk/emulator/emulator: No such file or directory
Exited with code exit status 127
```
