### ISSUE TITLE
Don't understand the new pod install command.

### ISSUE THREAD

**Issue by compojoom** [react-native-community/react-native-circleci-orb#58]
Hi guys,

I was on version 2.x and decided I'll update to version 4. I read the changelog and saw that there is a new pod install command. Here is the pull request for it:
https://github.com/react-native-community/react-native-circleci-orb/pull/48

The source code of the command is here: https://github.com/react-native-community/react-native-circleci-orb/blob/6507129208dda0db06e0ddcd1a3ee61fce287e78/src/commands/pod_install.yml

I was wondering why it doesn't have any cache and why it is supposed to be faster?

Previously I was using this:
```
  pod_install:
    description: Install POD dependencies
    steps:
      - restore_cache:
          keys:
            - mobileapp-pods-v1-{{ checksum "./ios/Podfile.lock" }}-{{ .Environment.CACHE_VERSION }}

      - run:
          name: Install pods
          command: "cd ios && pod install && cd .."
      - save_cache:
          key: mobileapp-pods-v1-{{ checksum "./ios/Podfile.lock" }}-{{ .Environment.CACHE_VERSION }}
          paths:
            - ./ios/Pods
```

But decided to swap my code for the pod install command. 
Now the pod install command in my project takes around 7mins. Where in the past (due to having cache most probobly) it was around 60s..

So why aren't we caching the pod dependencies now?
