### ISSUE TITLE
When running android_test it throws cmd: Can't find service: package

### ISSUE THREAD

**Issue by lukebrandonfarrell** [react-native-community/react-native-circleci-orb#81]
First off, thanks very much for the effort put into this library! It has saved a tone of time and is really well thought-out and built. My issue is that I am having trouble running the `android_test` command. I followed the setup and docs but the CI gives me issues. I am wondering if the docs are missing some sort of install or Circle CI setup step?

This is the configuration I am using:

```yml
  - react_native/android_build:
      name: build_android_release
      project_path: 'android'
      build_type: release
      requires:
        - analyse_js
  - react_native/android_test:
      name: test_android_release
      detox_configuration: 'android.emu.release'
      requires:
        - build_android_release
```

### What happened

```
detox[6799] INFO:  [test.js] DETOX_CONFIGURATION="android" DETOX_FORCE_ADB_INSTALL=false DETOX_HEADLESS=true DETOX_LOGLEVEL="warn" DETOX_READ_ONLY_EMU=false DETOX_REPORT_SPECS=true DETOX_START_TIMESTAMP=1612191220884 DETOX_USE_CUSTOM_LOGGER=true jest --config e2e/config.json --testNamePattern '^((?!:ios:).)*$' --maxWorkers 1 e2e
detox[7045] ERROR: Error: Exceeded timeout of 300000ms while handling jest-circus "setup" event

detox[7045] ERROR: DetoxRuntimeError: Aborted detox.init() execution, and now running detox.cleanup()

HINT: Most likely, your test runner is tearing down the suite due to the timeout error
detox[7045] ERROR: [exec.js/EXEC_FAIL, #15] ""/usr/local/share/android-sdk/platform-tools/adb" -s emulator-5554 shell "pm install -r -g -t /data/local/tmp/detox/Application.apk"" failed with code = 20, stdout and stderr:

detox[7045] ERROR: [exec.js/EXEC_FAIL, #15] 
detox[7045] ERROR: [exec.js/EXEC_FAIL, #15] cmd: Can't find service: package

detox[7045] ERROR: [exec.js/EXEC_FAIL, #32] ""/usr/local/share/android-sdk/platform-tools/adb" -s emulator-5554 shell "pm install -r -g -t /data/local/tmp/detox/Application.apk"" failed with code = 20, stdout and stderr:

detox[7045] ERROR: [exec.js/EXEC_FAIL, #32] 
detox[7045] ERROR: [exec.js/EXEC_FAIL, #32] cmd: Can't find service: package

detox[7045] ERROR: ChildProcessError: Command failed: "/usr/local/share/android-sdk/platform-tools/adb" -s emulator-5554 shell "pm install -r -g -t /data/local/tmp/detox/Application.apk"
cmd: Can't find service: package
 `"/usr/local/share/android-sdk/platform-tools/adb" -s emulator-5554 shell "pm install -r -g -t /data/local/tmp/detox/Application.apk"` (exited with error code 20)

detox[7045] ERROR: [exec.js/EXEC_FAIL, #38] ""/usr/local/share/android-sdk/platform-tools/adb" -s emulator-5554 shell "settings put global animator_duration_scale 0"" failed with code = 20, stdout and stderr:

detox[7045] ERROR: [exec.js/EXEC_FAIL, #38] 
detox[7045] ERROR: [exec.js/EXEC_FAIL, #38] cmd: Can't find service: settings

detox[7045] ERROR: ChildProcessError: Command failed: "/usr/local/share/android-sdk/platform-tools/adb" -s emulator-5554 shell "settings put global animator_duration_scale 0"
cmd: Can't find service: settings
 `"/usr/local/share/android-sdk/platform-tools/adb" -s emulator-5554 shell "settings put global animator_duration_scale 0"` (exited with error code 20)

detox[7045] ERROR: [EmulatorLauncher.js/SPAWN_FAIL] `/usr/local/share/android-sdk/emulator/emulator -verbose -no-audio -no-boot-anim -no-window -port 19378 @TestingAVD -gpu host` failed with code 1
  err: ChildProcessError: `/usr/local/share/android-sdk/emulator/emulator -verbose -no-audio -no-boot-anim -no-window -port 19378 @TestingAVD -gpu host` failed with code 1
      at ChildProcess.<anonymous> (/Users/distiller/project/node_modules/child-process-promise/lib/index.js:132:23)
      at ChildProcess.emit (events.js:198:13)
      at maybeClose (internal/child_process.js:982:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
detox[7045] ERROR: [EmulatorLauncher.js/SPAWN_FAIL] emulator: autoconfig: -skin 768x1280
emulator: autoconfig: -skindir (null)
emulator: autoconfig: -kernel /usr/local/share/android-sdk/system-images/android-28/google_apis/x86//kernel-ranchu-64
emulator: Target arch = 'x86'
emulator: Auto-config: -qemu -cpu qemu32
emulator: Auto-detect: Kernel image requires new device naming scheme.
emulator: Auto-detect: Kernel does not support YAFFS2 partitions.
emulator: autoconfig: -ramdisk /usr/local/share/android-sdk/system-images/android-28/google_apis/x86//ramdisk.img
emulator: Using initial system image: /usr/local/share/android-sdk/system-images/android-28/google_apis/x86//system.img
emulator: Using initial vendor image: /usr/local/share/android-sdk/system-images/android-28/google_apis/x86//vendor.img
emulator: autoconfig: -data /Users/distiller/.android/avd/TestingAVD.avd/userdata-qemu.img
emulator: autoconfig: -initdata /Users/distiller/.android/avd/TestingAVD.avd/userdata.img
emulator: autoconfig: -cache /Users/distiller/.android/avd/TestingAVD.avd/cache.img
emulator: Increasing RAM size to 1536MB
emulator: VM heap size 0MB is below hardware specified minimum of 384MB,setting it to that value
emulator: System image is read only
emulator: Found 2 DNS servers: 8.8.8.8 8.8.4.4
emulator: ERROR: Running multiple emulators with the same AVD is an experimental feature.
Please use -read-only flag to enable this feature.


detox[7045] ERROR: ChildProcessError: `/usr/local/share/android-sdk/emulator/emulator -verbose -no-audio -no-boot-anim -no-window -port 19378 @TestingAVD -gpu host` failed with code 1

detox[6799] ERROR: [cli.js] Error: Command failed: jest --config e2e/config.json --testNamePattern '^((?!:ios:).)*$' --maxWorkers 1 e2e


Exited with code exit status 1
```

### Expected behavior

Ideally the tests should run without issues.

If there is some additional setup needed I happy to contribute to the docs.

**Comment by lukebrandonfarrell** [comment]
I was able to fix this with the following config (using the lower level commands instead):

```

orbs:
  react-native: react-native-community/react-native@4.4.2

jobs:
  android_test:
    macos:
      xcode: '11.3'
    steps:
      - checkout
      - react-native/setup_macos_executor
      - react-native/android_emulator_start
      - run: nc -z localhost 5037
      - react-native/yarn_install
      - react-native/detox_build:
          configuration: android.emu.release
      - react-native/detox_test:
          configuration: android.emu.release

workflows:
  test:
    jobs:
      - android_test
```
