### ISSUE TITLE
setup_macos_executor fails on detox configuration

### ISSUE THREAD

**Issue by Kyonru** [react-native-community/react-native-circleci-orb#93]
### Orb version
version: 5.1.0

### What happened

Build fails at step "Configure Detox Environment".

![image](https://user-images.githubusercontent.com/17935828/114418944-fe547880-9b80-11eb-9c57-8ae82be49f67.png)

<details><summary>Error transcript</summary>
<p>

```bash
#!/bin/bash --login -eo pipefail
HOMEBREW_NO_AUTO_UPDATE=1 brew tap wix/brew >/dev/null
HOMEBREW_NO_AUTO_UPDATE=1 brew tap homebrew/cask >/dev/null
HOMEBREW_NO_AUTO_UPDATE=1 brew install applesimutils >/dev/null
HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask android-sdk >/dev/null
touch .watchmanconfig
node -v
```

```bash
==> Tapping wix/brew
Cloning into '/usr/local/Homebrew/Library/Taps/wix/homebrew-brew'...
remote: Enumerating objects: 78, done.        
remote: Counting objects: 100% (78/78), done.        
remote: Compressing objects: 100% (44/44), done.        
remote: Total 622 (delta 41), reused 58 (delta 22), pack-reused 544        
Receiving objects: 100% (622/622), 1.58 MiB | 9.14 MiB/s, done.
Resolving deltas: 100% (328/328), done.
Tapped 1 cask and 1 formula (31 files, 1.6MB).
==> Tapping homebrew/cask
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask'...
remote: Enumerating objects: 373, done.        
remote: Counting objects: 100% (373/373), done.        
remote: Compressing objects: 100% (222/222), done.        
remote: Total 563812 (delta 194), reused 290 (delta 151), pack-reused 563439        
Receiving objects: 100% (563812/563812), 248.93 MiB | 15.03 MiB/s, done.
Resolving deltas: 100% (398150/398150), done.
Error: Invalid cask: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/emacs.rb
Cask ''/Applications/Emacs.app/Contents/Resources/man/man1/ebrowse.1.gz' is not a valid man page name' definition is invalid.
Error: Cannot tap homebrew/cask: invalid syntax in tap!
```

```
Exited with code exit status 1
CircleCI received exit code 1
```
</p>
</details>

### Expected behavior

Detox environment is configured. `brew tap homebrew/cask` does not fail.

**Comment by Kyonru** [comment]
Closing this since it was an issue with https://github.com/Homebrew/homebrew-cask/pull/103373.

**Comment by clintonb** [comment]
@Kyonru is the solution here to upgrade homebrew on CircleCI?

**Comment by Kyonru** [comment]
@clintonb yes, this should probably be reopened, since we cannot use `homebrew_cache: false` for the mac executor in the android job. I end up implementing most of the jobs using the orb commands. Even did a post about it. https://dev.to/kyonru/react-native-e2e-tests-and-automatic-deploys-detox-fastlane-circleci-3gkn

But the solution would be having homebrew_cache exposed in `jobs/android_tes`.

**Comment by clintonb** [comment]
@Kyonru I think we are discussing two different issues. I don't think brew is run for Android builds. It seems a simpler solution is to update Homebrew to 3.1.1+.

**Comment by Kyonru** [comment]
@clintonb maybe running brew update before `android_test`, can help.

**Comment by clintonb** [comment]
Again, the issue is with iOS, not Android. I get the exact same error that you described in your initial comment on this issue. I tried running `brew update` but it didn't work. Rather than having everyone manually update brew, it would be ideal if the orb did it for us since the orb requires brew.

Here is my config.yml:
```yaml
jobs:
  analyse_js:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - run:
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          name: Configure NPM token
      - rn/yarn_install
      - run:
          command: yarn eslint
          name: Run ESLint
# TODO Reactivate once broken tests fixed
#      - run:
#          command: yarn jest
#          name: Jest
  checkout_code:
    executor: rn/linux_js
    steps:
      - checkout
      - persist_to_workspace:
          paths: .
          root: .
  update_homebrew:
    executor: rn/macos
    steps:
      - run:
          command: HOMEBREW_NO_AUTO_UPDATE=1 brew update
          name: Update Homebrew
      - persist_to_workspace:
          paths: .
          root: .
  fastlane_android_release:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - run:
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          name: Configure NPM token
      - rn/yarn_install
      - run:
          command: echo
          name: Run Fastlane
  fastlane_ios_release:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - run:
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          name: Configure NPM token
      - rn/yarn_install
      - run:
          command: echo 1
          name: Run Fastlane
orbs:
  rn: react-native-community/react-native@5.1.0
version: 2.1
workflows:
  test:
    jobs:
      - checkout_code
      - analyse_js:
          requires:
            - checkout_code
      - rn/android_build:
          build_type: debug
          name: build_android_debug
          project_path: android
          requires:
            - analyse_js
      - rn/android_build:
          build_type: release
          name: build_android_release
          project_path: android
          requires:
            - analyse_js
      - rn/android_test:
          detox_configuration: android.emu.release
          requires:
            - build_android_release
      - update_homebrew
      - rn/ios_build:
          build_configuration: Release
          device: iPhone X
          name: build_ios_release
          project_path: ios/redacted.xcworkspace
          requires:
            - analyse_js
            - update_homebrew
          scheme: redacted
      - rn/ios_build_and_test:
          build_configuration: Release
          detox_configuration: ios.sim.release
          device: iPhone X
          project_path: ios/redacted.xcworkspace
          requires:
            - analyse_js
            - update_homebrew
          scheme: redacted
      - fastlane_android_release:
          requires:
            - rn/android_test
      - fastlane_ios_release:
          requires:
            - rn/ios_build_and_test
```
